# Site settings
title: dev._.had Blog
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "https://hadongkyoun.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dev._.had
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Web Developer
email: gkehdrbs36@naver.com
twitter_username: lorem_ipsum
github_username:  hadongkyoun
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "gkehdrbs36@gmail.com"

exclude: ['package.json', 'src' , 'node_modules']
