# Site settings
title: dev._.had Blog
description: dev._.had Blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "https://hadongkyoun.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dev._.had
user_description:
user_title: Web Developer
email: gkehdrbs36@naver.com
twitter_username: lorem_ipsum
github_username:  hadongkyoun
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "gkehdrbs36@gmail.com"

exclude: ['package.json', 'src' , 'node_modules']
